name: Flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call: # Usually called from deploy

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: cp install/package.json package.json

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Flow Init
        run: npm run flow init
      
      - name: Run Flow
        run: npm run flow
